"""add all tables

Revision ID: cd42b4a4857b
Revises: 
Create Date: 2021-07-03 21:59:12.119546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd42b4a4857b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenity_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('possible_attributes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenity_categories_code'), 'amenity_categories', ['code'], unique=False)
    op.create_index(op.f('ix_amenity_categories_description'), 'amenity_categories', ['description'], unique=False)
    op.create_index(op.f('ix_amenity_categories_id'), 'amenity_categories', ['id'], unique=False)
    op.create_index(op.f('ix_amenity_categories_notes'), 'amenity_categories', ['notes'], unique=False)
    op.create_index(op.f('ix_amenity_categories_possible_attributes'), 'amenity_categories', ['possible_attributes'], unique=False)
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('nightly_price', sa.Float(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('available_count', sa.Integer(), nullable=True),
    sa.Column('min_los', sa.Integer(), nullable=True),
    sa.Column('max_los', sa.Integer(), nullable=True),
    sa.Column('closed_to_arrival', sa.Boolean(), nullable=True),
    sa.Column('closed_to_departure', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_end_date'), 'calendar', ['end_date'], unique=False)
    op.create_index(op.f('ix_calendar_id'), 'calendar', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_start_date'), 'calendar', ['start_date'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('discount_code', sa.String(length=100), nullable=True),
    sa.Column('discount_description', sa.String(length=100), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=True),
    sa.Column('rule_value', sa.String(length=100), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('channel_contribution', sa.Float(), nullable=True),
    sa.Column('pm_contribution', sa.String(length=100), nullable=True),
    sa.Column('min_adr', sa.String(length=100), nullable=True),
    sa.Column('max_adr', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_discount_code'), 'discount', ['discount_code'], unique=False)
    op.create_index(op.f('ix_discount_discount_description'), 'discount', ['discount_description'], unique=False)
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    op.create_index(op.f('ix_discount_max_adr'), 'discount', ['max_adr'], unique=False)
    op.create_index(op.f('ix_discount_min_adr'), 'discount', ['min_adr'], unique=False)
    op.create_index(op.f('ix_discount_pm_contribution'), 'discount', ['pm_contribution'], unique=False)
    op.create_index(op.f('ix_discount_rule_name'), 'discount', ['rule_name'], unique=False)
    op.create_index(op.f('ix_discount_rule_value'), 'discount', ['rule_value'], unique=False)
    op.create_table('listing_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_contacts_email_address'), 'listing_contacts', ['email_address'], unique=False)
    op.create_index(op.f('ix_listing_contacts_id'), 'listing_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_listing_contacts_name'), 'listing_contacts', ['name'], unique=False)
    op.create_index(op.f('ix_listing_contacts_phone'), 'listing_contacts', ['phone'], unique=False)
    op.create_index(op.f('ix_listing_contacts_type'), 'listing_contacts', ['type'], unique=False)
    op.create_table('listing_policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_policy_category', sa.String(length=100), nullable=True),
    sa.Column('check_in_start_time', sa.String(length=100), nullable=True),
    sa.Column('check_in_end_time', sa.String(length=100), nullable=True),
    sa.Column('check_out_time', sa.String(length=100), nullable=True),
    sa.Column('security_deposit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_policy_cancellation_policy_category'), 'listing_policy', ['cancellation_policy_category'], unique=False)
    op.create_index(op.f('ix_listing_policy_check_in_end_time'), 'listing_policy', ['check_in_end_time'], unique=False)
    op.create_index(op.f('ix_listing_policy_check_in_start_time'), 'listing_policy', ['check_in_start_time'], unique=False)
    op.create_index(op.f('ix_listing_policy_check_out_time'), 'listing_policy', ['check_out_time'], unique=False)
    op.create_index(op.f('ix_listing_policy_id'), 'listing_policy', ['id'], unique=False)
    op.create_index(op.f('ix_listing_policy_security_deposit'), 'listing_policy', ['security_deposit'], unique=False)
    op.create_table('listing_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(length=100), nullable=True),
    sa.Column('price_change', sa.Integer(), nullable=True),
    sa.Column('price_change_type', sa.String(length=100), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_price_end_date'), 'listing_price', ['end_date'], unique=False)
    op.create_index(op.f('ix_listing_price_id'), 'listing_price', ['id'], unique=False)
    op.create_index(op.f('ix_listing_price_price_change_type'), 'listing_price', ['price_change_type'], unique=False)
    op.create_index(op.f('ix_listing_price_rule_type'), 'listing_price', ['rule_type'], unique=False)
    op.create_index(op.f('ix_listing_price_start_date'), 'listing_price', ['start_date'], unique=False)
    op.create_table('listing_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_status_id'), 'listing_status', ['id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('caption', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('locale', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_caption'), 'photos', ['caption'], unique=False)
    op.create_index(op.f('ix_photos_content_type'), 'photos', ['content_type'], unique=False)
    op.create_index(op.f('ix_photos_filename'), 'photos', ['filename'], unique=False)
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.create_index(op.f('ix_photos_locale'), 'photos', ['locale'], unique=False)
    op.create_index(op.f('ix_photos_tags'), 'photos', ['tags'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_policy_category', sa.String(length=100), nullable=True),
    sa.Column('confirmation_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.String(length=100), nullable=True),
    sa.Column('booked_at', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('guest_email', sa.String(length=100), nullable=True),
    sa.Column('guest_first_name', sa.String(length=100), nullable=True),
    sa.Column('guest_last_name', sa.String(length=100), nullable=True),
    sa.Column('guest_phone_numbers', sa.String(length=100), nullable=True),
    sa.Column('guest_preferred_locale', sa.String(length=100), nullable=True),
    sa.Column('nightly_base_price', sa.Float(), nullable=True),
    sa.Column('cancellation_fee', sa.String(length=100), nullable=True),
    sa.Column('commission_amount', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=100), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('number_of_guests', sa.Integer(), nullable=True),
    sa.Column('tax_amount', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('total', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('trip_purpose', sa.String(length=100), nullable=True),
    sa.Column('discount_code', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_booked_at'), 'reservation', ['booked_at'], unique=False)
    op.create_index(op.f('ix_reservation_cancellation_fee'), 'reservation', ['cancellation_fee'], unique=False)
    op.create_index(op.f('ix_reservation_cancellation_policy_category'), 'reservation', ['cancellation_policy_category'], unique=False)
    op.create_index(op.f('ix_reservation_commission_amount'), 'reservation', ['commission_amount'], unique=False)
    op.create_index(op.f('ix_reservation_confirmation_code'), 'reservation', ['confirmation_code'], unique=False)
    op.create_index(op.f('ix_reservation_created_at'), 'reservation', ['created_at'], unique=False)
    op.create_index(op.f('ix_reservation_currency'), 'reservation', ['currency'], unique=False)
    op.create_index(op.f('ix_reservation_discount_code'), 'reservation', ['discount_code'], unique=False)
    op.create_index(op.f('ix_reservation_end_date'), 'reservation', ['end_date'], unique=False)
    op.create_index(op.f('ix_reservation_guest_email'), 'reservation', ['guest_email'], unique=False)
    op.create_index(op.f('ix_reservation_guest_first_name'), 'reservation', ['guest_first_name'], unique=False)
    op.create_index(op.f('ix_reservation_guest_last_name'), 'reservation', ['guest_last_name'], unique=False)
    op.create_index(op.f('ix_reservation_guest_phone_numbers'), 'reservation', ['guest_phone_numbers'], unique=False)
    op.create_index(op.f('ix_reservation_guest_preferred_locale'), 'reservation', ['guest_preferred_locale'], unique=False)
    op.create_index(op.f('ix_reservation_id'), 'reservation', ['id'], unique=False)
    op.create_index(op.f('ix_reservation_ip_address'), 'reservation', ['ip_address'], unique=False)
    op.create_index(op.f('ix_reservation_notes'), 'reservation', ['notes'], unique=False)
    op.create_index(op.f('ix_reservation_session_id'), 'reservation', ['session_id'], unique=False)
    op.create_index(op.f('ix_reservation_start_date'), 'reservation', ['start_date'], unique=False)
    op.create_index(op.f('ix_reservation_status'), 'reservation', ['status'], unique=False)
    op.create_index(op.f('ix_reservation_tax_amount'), 'reservation', ['tax_amount'], unique=False)
    op.create_index(op.f('ix_reservation_total'), 'reservation', ['total'], unique=False)
    op.create_index(op.f('ix_reservation_trip_purpose'), 'reservation', ['trip_purpose'], unique=False)
    op.create_index(op.f('ix_reservation_updated_at'), 'reservation', ['updated_at'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=100), nullable=True),
    sa.Column('bed_type', sa.String(length=100), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('bath_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_bed_type'), 'rooms', ['bed_type'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_room_type'), 'rooms', ['room_type'], unique=False)
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.String(length=100), nullable=True),
    sa.Column('card_month', sa.String(length=100), nullable=True),
    sa.Column('card_year', sa.String(length=100), nullable=True),
    sa.Column('card_type', sa.String(length=100), nullable=True),
    sa.Column('cc_security_code', sa.String(length=100), nullable=True),
    sa.Column('cc_address', sa.String(length=100), nullable=True),
    sa.Column('cc_country', sa.String(length=100), nullable=True),
    sa.Column('cc_state', sa.String(length=100), nullable=True),
    sa.Column('cc_city', sa.String(length=100), nullable=True),
    sa.Column('cc_birth_date', sa.Date(), nullable=True),
    sa.Column('cc_zipcode', sa.String(length=100), nullable=True),
    sa.Column('cc_first_name', sa.String(length=100), nullable=True),
    sa.Column('cc_last_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_card_month'), 'credit_card', ['card_month'], unique=False)
    op.create_index(op.f('ix_credit_card_card_number'), 'credit_card', ['card_number'], unique=False)
    op.create_index(op.f('ix_credit_card_card_type'), 'credit_card', ['card_type'], unique=False)
    op.create_index(op.f('ix_credit_card_card_year'), 'credit_card', ['card_year'], unique=False)
    op.create_index(op.f('ix_credit_card_cc_address'), 'credit_card', ['cc_address'], unique=False)
    op.create_index(op.f('ix_credit_card_cc_birth_date'), 'credit_card', ['cc_birth_date'], unique=False)
    op.create_index(op.f('ix_credit_card_cc_city'), 'credit_card', ['cc_city'], unique=False)
    op.create_index(op.f('ix_credit_card_cc_country'), 'credit_card', ['cc_country'], unique=False)
    op.create_index(op.f('ix_credit_card_cc_first_name'), 'credit_card', ['cc_first_name'], unique=False)
    op.create_index(op.f('ix_credit_card_cc_last_name'), 'credit_card', ['cc_last_name'], unique=False)
    op.create_index(op.f('ix_credit_card_cc_security_code'), 'credit_card', ['cc_security_code'], unique=False)
    op.create_index(op.f('ix_credit_card_cc_state'), 'credit_card', ['cc_state'], unique=False)
    op.create_index(op.f('ix_credit_card_cc_zipcode'), 'credit_card', ['cc_zipcode'], unique=False)
    op.create_index(op.f('ix_credit_card_id'), 'credit_card', ['id'], unique=False)
    op.create_table('fees_and_taxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_policy_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('fee_tax_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('charge_frequency', sa.Integer(), nullable=True),
    sa.Column('charge_type', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('charged_at', sa.String(length=100), nullable=True),
    sa.Column('room_id', sa.String(length=100), nullable=True),
    sa.Column('min_guests', sa.Integer(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_policy_id'], ['listing_policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fees_and_taxes_charged_at'), 'fees_and_taxes', ['charged_at'], unique=False)
    op.create_index(op.f('ix_fees_and_taxes_description'), 'fees_and_taxes', ['description'], unique=False)
    op.create_index(op.f('ix_fees_and_taxes_fee_tax_id'), 'fees_and_taxes', ['fee_tax_id'], unique=False)
    op.create_index(op.f('ix_fees_and_taxes_id'), 'fees_and_taxes', ['id'], unique=False)
    op.create_index(op.f('ix_fees_and_taxes_room_id'), 'fees_and_taxes', ['room_id'], unique=False)
    op.create_index(op.f('ix_fees_and_taxes_type'), 'fees_and_taxes', ['type'], unique=False)
    op.create_table('guest_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_policy_id', sa.Integer(), nullable=True),
    sa.Column('smoking_allowed', sa.Boolean(), nullable=True),
    sa.Column('parties_allowed', sa.Boolean(), nullable=True),
    sa.Column('parking_allowed', sa.String(length=20), nullable=True),
    sa.Column('parking_price_type', sa.String(length=20), nullable=True),
    sa.Column('pets_allowed', sa.String(length=20), nullable=True),
    sa.Column('pets_price_type', sa.String(length=20), nullable=True),
    sa.Column('quiet_hours_set', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_start_time', sa.String(length=100), nullable=True),
    sa.Column('quiet_hours_end_time', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['listing_policy_id'], ['listing_policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_policies_id'), 'guest_policies', ['id'], unique=False)
    op.create_index(op.f('ix_guest_policies_parking_allowed'), 'guest_policies', ['parking_allowed'], unique=False)
    op.create_index(op.f('ix_guest_policies_parking_price_type'), 'guest_policies', ['parking_price_type'], unique=False)
    op.create_index(op.f('ix_guest_policies_pets_allowed'), 'guest_policies', ['pets_allowed'], unique=False)
    op.create_index(op.f('ix_guest_policies_pets_price_type'), 'guest_policies', ['pets_price_type'], unique=False)
    op.create_index(op.f('ix_guest_policies_quiet_hours_end_time'), 'guest_policies', ['quiet_hours_end_time'], unique=False)
    op.create_index(op.f('ix_guest_policies_quiet_hours_start_time'), 'guest_policies', ['quiet_hours_start_time'], unique=False)
    op.create_table('key_collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_policy_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('check_in_method', sa.String(length=100), nullable=True),
    sa.Column('how', sa.String(length=100), nullable=True),
    sa.Column('when', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['listing_policy_id'], ['listing_policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_collection_check_in_method'), 'key_collection', ['check_in_method'], unique=False)
    op.create_index(op.f('ix_key_collection_how'), 'key_collection', ['how'], unique=False)
    op.create_index(op.f('ix_key_collection_id'), 'key_collection', ['id'], unique=False)
    op.create_index(op.f('ix_key_collection_type'), 'key_collection', ['type'], unique=False)
    op.create_index(op.f('ix_key_collection_when'), 'key_collection', ['when'], unique=False)
    op.create_table('los_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('los_value', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_los_price_currency'), 'los_price', ['currency'], unique=False)
    op.create_index(op.f('ix_los_price_id'), 'los_price', ['id'], unique=False)
    op.create_table('reservation_fees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('discounted_amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('sub_type', sa.String(length=100), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_fees_description'), 'reservation_fees', ['description'], unique=False)
    op.create_index(op.f('ix_reservation_fees_id'), 'reservation_fees', ['id'], unique=False)
    op.create_index(op.f('ix_reservation_fees_sub_type'), 'reservation_fees', ['sub_type'], unique=False)
    op.create_index(op.f('ix_reservation_fees_type'), 'reservation_fees', ['type'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('reward_number', sa.Integer(), nullable=True),
    sa.Column('reward_email', sa.String(length=100), nullable=True),
    sa.Column('reward_level', sa.String(length=100), nullable=True),
    sa.Column('reward_points_used', sa.Integer(), nullable=True),
    sa.Column('reward_points_earn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_id'), 'rewards', ['id'], unique=False)
    op.create_index(op.f('ix_rewards_reward_email'), 'rewards', ['reward_email'], unique=False)
    op.create_index(op.f('ix_rewards_reward_level'), 'rewards', ['reward_level'], unique=False)
    op.create_index(op.f('ix_listing_apt'), 'listing', ['apt'], unique=False)
    op.create_index(op.f('ix_listing_beds'), 'listing', ['beds'], unique=False)
    op.create_index(op.f('ix_listing_check_in_option'), 'listing', ['check_in_option'], unique=False)
    op.create_index(op.f('ix_listing_city'), 'listing', ['city'], unique=False)
    op.create_index(op.f('ix_listing_country_code'), 'listing', ['country_code'], unique=False)
    op.create_index(op.f('ix_listing_lat'), 'listing', ['lat'], unique=False)
    op.create_index(op.f('ix_listing_listing_currency'), 'listing', ['listing_currency'], unique=False)
    op.create_index(op.f('ix_listing_lng'), 'listing', ['lng'], unique=False)
    op.create_index(op.f('ix_listing_person_capacity'), 'listing', ['person_capacity'], unique=False)
    op.create_index(op.f('ix_listing_short_description'), 'listing', ['short_description'], unique=False)
    op.create_index(op.f('ix_listing_state'), 'listing', ['state'], unique=False)
    op.create_index(op.f('ix_listing_street'), 'listing', ['street'], unique=False)
    op.create_index(op.f('ix_listing_zipcode'), 'listing', ['zipcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_zipcode'), table_name='listing')
    op.drop_index(op.f('ix_listing_street'), table_name='listing')
    op.drop_index(op.f('ix_listing_state'), table_name='listing')
    op.drop_index(op.f('ix_listing_short_description'), table_name='listing')
    op.drop_index(op.f('ix_listing_person_capacity'), table_name='listing')
    op.drop_index(op.f('ix_listing_lng'), table_name='listing')
    op.drop_index(op.f('ix_listing_listing_currency'), table_name='listing')
    op.drop_index(op.f('ix_listing_lat'), table_name='listing')
    op.drop_index(op.f('ix_listing_country_code'), table_name='listing')
    op.drop_index(op.f('ix_listing_city'), table_name='listing')
    op.drop_index(op.f('ix_listing_check_in_option'), table_name='listing')
    op.drop_index(op.f('ix_listing_beds'), table_name='listing')
    op.drop_index(op.f('ix_listing_apt'), table_name='listing')
    op.drop_index(op.f('ix_rewards_reward_level'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_reward_email'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_reservation_fees_type'), table_name='reservation_fees')
    op.drop_index(op.f('ix_reservation_fees_sub_type'), table_name='reservation_fees')
    op.drop_index(op.f('ix_reservation_fees_id'), table_name='reservation_fees')
    op.drop_index(op.f('ix_reservation_fees_description'), table_name='reservation_fees')
    op.drop_table('reservation_fees')
    op.drop_index(op.f('ix_los_price_id'), table_name='los_price')
    op.drop_index(op.f('ix_los_price_currency'), table_name='los_price')
    op.drop_table('los_price')
    op.drop_index(op.f('ix_key_collection_when'), table_name='key_collection')
    op.drop_index(op.f('ix_key_collection_type'), table_name='key_collection')
    op.drop_index(op.f('ix_key_collection_id'), table_name='key_collection')
    op.drop_index(op.f('ix_key_collection_how'), table_name='key_collection')
    op.drop_index(op.f('ix_key_collection_check_in_method'), table_name='key_collection')
    op.drop_table('key_collection')
    op.drop_index(op.f('ix_guest_policies_quiet_hours_start_time'), table_name='guest_policies')
    op.drop_index(op.f('ix_guest_policies_quiet_hours_end_time'), table_name='guest_policies')
    op.drop_index(op.f('ix_guest_policies_pets_price_type'), table_name='guest_policies')
    op.drop_index(op.f('ix_guest_policies_pets_allowed'), table_name='guest_policies')
    op.drop_index(op.f('ix_guest_policies_parking_price_type'), table_name='guest_policies')
    op.drop_index(op.f('ix_guest_policies_parking_allowed'), table_name='guest_policies')
    op.drop_index(op.f('ix_guest_policies_id'), table_name='guest_policies')
    op.drop_table('guest_policies')
    op.drop_index(op.f('ix_fees_and_taxes_type'), table_name='fees_and_taxes')
    op.drop_index(op.f('ix_fees_and_taxes_room_id'), table_name='fees_and_taxes')
    op.drop_index(op.f('ix_fees_and_taxes_id'), table_name='fees_and_taxes')
    op.drop_index(op.f('ix_fees_and_taxes_fee_tax_id'), table_name='fees_and_taxes')
    op.drop_index(op.f('ix_fees_and_taxes_description'), table_name='fees_and_taxes')
    op.drop_index(op.f('ix_fees_and_taxes_charged_at'), table_name='fees_and_taxes')
    op.drop_table('fees_and_taxes')
    op.drop_index(op.f('ix_credit_card_id'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_cc_zipcode'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_cc_state'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_cc_security_code'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_cc_last_name'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_cc_first_name'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_cc_country'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_cc_city'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_cc_birth_date'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_cc_address'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_card_year'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_card_type'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_card_number'), table_name='credit_card')
    op.drop_index(op.f('ix_credit_card_card_month'), table_name='credit_card')
    op.drop_table('credit_card')
    op.drop_index(op.f('ix_rooms_room_type'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_bed_type'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_reservation_updated_at'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_trip_purpose'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_total'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_tax_amount'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_status'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_start_date'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_session_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_notes'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_ip_address'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_guest_preferred_locale'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_guest_phone_numbers'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_guest_last_name'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_guest_first_name'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_guest_email'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_end_date'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_discount_code'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_currency'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_created_at'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_confirmation_code'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_commission_amount'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_cancellation_policy_category'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_cancellation_fee'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_booked_at'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_photos_tags'), table_name='photos')
    op.drop_index(op.f('ix_photos_locale'), table_name='photos')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_filename'), table_name='photos')
    op.drop_index(op.f('ix_photos_content_type'), table_name='photos')
    op.drop_index(op.f('ix_photos_caption'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_listing_status_id'), table_name='listing_status')
    op.drop_table('listing_status')
    op.drop_index(op.f('ix_listing_price_start_date'), table_name='listing_price')
    op.drop_index(op.f('ix_listing_price_rule_type'), table_name='listing_price')
    op.drop_index(op.f('ix_listing_price_price_change_type'), table_name='listing_price')
    op.drop_index(op.f('ix_listing_price_id'), table_name='listing_price')
    op.drop_index(op.f('ix_listing_price_end_date'), table_name='listing_price')
    op.drop_table('listing_price')
    op.drop_index(op.f('ix_listing_policy_security_deposit'), table_name='listing_policy')
    op.drop_index(op.f('ix_listing_policy_id'), table_name='listing_policy')
    op.drop_index(op.f('ix_listing_policy_check_out_time'), table_name='listing_policy')
    op.drop_index(op.f('ix_listing_policy_check_in_start_time'), table_name='listing_policy')
    op.drop_index(op.f('ix_listing_policy_check_in_end_time'), table_name='listing_policy')
    op.drop_index(op.f('ix_listing_policy_cancellation_policy_category'), table_name='listing_policy')
    op.drop_table('listing_policy')
    op.drop_index(op.f('ix_listing_contacts_type'), table_name='listing_contacts')
    op.drop_index(op.f('ix_listing_contacts_phone'), table_name='listing_contacts')
    op.drop_index(op.f('ix_listing_contacts_name'), table_name='listing_contacts')
    op.drop_index(op.f('ix_listing_contacts_id'), table_name='listing_contacts')
    op.drop_index(op.f('ix_listing_contacts_email_address'), table_name='listing_contacts')
    op.drop_table('listing_contacts')
    op.drop_index(op.f('ix_discount_rule_value'), table_name='discount')
    op.drop_index(op.f('ix_discount_rule_name'), table_name='discount')
    op.drop_index(op.f('ix_discount_pm_contribution'), table_name='discount')
    op.drop_index(op.f('ix_discount_min_adr'), table_name='discount')
    op.drop_index(op.f('ix_discount_max_adr'), table_name='discount')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_index(op.f('ix_discount_discount_description'), table_name='discount')
    op.drop_index(op.f('ix_discount_discount_code'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_calendar_start_date'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_id'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_end_date'), table_name='calendar')
    op.drop_table('calendar')
    op.drop_index(op.f('ix_amenity_categories_possible_attributes'), table_name='amenity_categories')
    op.drop_index(op.f('ix_amenity_categories_notes'), table_name='amenity_categories')
    op.drop_index(op.f('ix_amenity_categories_id'), table_name='amenity_categories')
    op.drop_index(op.f('ix_amenity_categories_description'), table_name='amenity_categories')
    op.drop_index(op.f('ix_amenity_categories_code'), table_name='amenity_categories')
    op.drop_table('amenity_categories')
    # ### end Alembic commands ###
